<script setup lang="ts">
import PageHeader from '~/components/ui/PageHeader.vue'
useHead({ title: 'Methodology' })
const principles = [
  {
    number: '01',
    title: 'Seeded and versioned',
    text: 'Source events are generated by a deterministic PRNG from a named seed and versioned Northstar scenario. The fixed UTC reference period runs from 1 July 2025 through 30 June 2026.'
  },
  {
    number: '02',
    title: 'Stories with testable direction',
    text: 'The 10,000-event development profile encodes a launch spike, Harbor Hall strength, a mobile Safari issue, channel-quality contrasts, and time patterns. They are synthetic relationships, not causal claims.'
  },
  {
    number: '03',
    title: 'Validated and reproducible',
    text: 'Structured integrity checks cover catalog references, time ranges, QR associations, session order and conversion context. A stable content fingerprint proves reproducibility.'
  },
  {
    number: '04',
    title: 'Honest product boundaries',
    text: 'The current charts and displayed metrics remain a clearly separated presentation snapshot. Analytics execution, Web Workers and million-event benchmarks are not implemented.'
  }
]
</script>
<template>
  <div class="page methodology-page">
    <PageHeader
      eyebrow="Methodology"
      title="A product shell with explicit evidence boundaries."
      description="How Phase 2 establishes trustworthy source semantics without claiming an analytics engine."
    />
    <section class="methodology-hero">
      <p class="methodology-hero__quote">
        “A useful analytical product makes the limits of its evidence as legible as the signal.”
      </p>
      <div><span>Phase</span><strong>02 · Domain data</strong></div>
    </section>
    <section class="principle-list">
      <article v-for="principle in principles" :key="principle.number">
        <span>{{ principle.number }}</span>
        <div>
          <h2>{{ principle.title }}</h2>
          <p>{{ principle.text }}</p>
        </div>
      </article>
    </section>
    <section class="scope-table panel">
      <div>
        <p class="eyebrow">Delivery boundary</p>
        <h2>What this phase proves</h2>
      </div>
      <div class="scope-columns">
        <div>
          <h3>Implemented now</h3>
          <ul>
            <li>Typed domain model and reference catalog</li>
            <li>Seeded test and 10K development profiles</li>
            <li>Versioned behavioral scenario and fingerprint</li>
            <li>Structured dataset integrity validation</li>
          </ul>
        </div>
        <div>
          <h3>Deliberately deferred</h3>
          <ul>
            <li>Analytics execution and aggregation</li>
            <li>Web Worker, indexes and query cache</li>
            <li>Million-event generation and benchmarks</li>
            <li>Real QR generation or export</li>
            <li>PDF and presentation generation</li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</template>
